language: python
os: linux
dist: bionic

jobs:
  include:
    - python: 3.6
      env: PYVERSION=36
    - python: 3.7
      env: PYVERSION=37
    - python: 3.8
      env: PYVERSION=38

before_install:
  - sudo apt-get install jq curl

install:
  - pip install -q pytest pytest-runner pytest-cov coverage codacy-coverage
  - pip install coveralls
  - pip install -e .[skl,stats] # install skl, statsmodels

script:
  - xvfb-run python setup.py test

after_success:
  - "ls -lr htmlcov"
  - coveralls # coverage to coveralls.io
  - python-codacy-coverage -r coverage.xml
