name: pyrolitedocs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - matplotlib
  - scipy>=1.2
  - pandas>=0.23
  - pip:
      - -e git+https://github.com/morganjwilliams/pyrolite.git@develop#egg=pyrolite[dev,skl]
